### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by turtle2472** [garelp/zabbix-minecraft-server#1]
Would you mind providing a little more documentation on how to implement this in the readme file?  I'm new to Zabbix but would like to be able to monitor my MC servers.

**Comment by garelp** [comment]
Hello..

Sure I'll write a little doc on how to use it.

**Comment by garelp** [comment]
Documentation updated.

**Comment by turtle2472** [comment]
Thanks for the documentation help!  I assume that the minecraftparam.conf and stats_mcserver.py go on the Minecraft server while the template is imported into the Zabbix Server.

**Comment by garelp** [comment]
Yes you're right. I've updated the doc accordingly. 

Thanks.

**Comment by turtle2472** [comment]
Thank you very much for they help with that.  It makes it easier for a novice like me to get it running.  It's running and works great.  Thanks!
